name: Test getinfo.py

on:
  push:
    branches: [main]
  pull_request:

jobs:

  run-getinfo:
    name: python getinfo.py ${{ matrix.python-version }}/${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
          - macos-12
          - macos-13
          - macos-14
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        include:
          - os: macos-14
            python-version: '3.8'
            unavailable: "true"
          - os: macos-14
            python-version: '3.9'
            unavailable: "true"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ !matrix.unavailable }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python getinfo.py --help
      - run: python getinfo.py --version
      - run: python getinfo.py
      - run: python getinfo.py -o stdout
      - run: python getinfo.py -o getinfo-output.json
